version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependency
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: persist file
          command: mv ./build /tmp/workspace/build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '3d:87:8e:9f:a6:94:27:37:48:ff:6f:76:76:58:6b:72'
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: transfer file
          command: cd /tmp/workspace && ls && scp -r ./build $SSH_USER@$SSH_HOST:~/github-timeline/build-tmp
      - run:
          name: deploy
          command: |
            ssh $SSH_USER@$SSH_HOST "cd github-timeline && \
            mv build build-old && \
            mv build-tmp build && \
            rm -rf build-old"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
